import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#002109",
        "primary-container": "#131b2e",
        "on-secondary": "#ffffff",
        "primary": "#000000",
        "surface-container-highest": "#e0e3e5",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#eceef0",
        "secondary-container": "#316bf3",
        "primary-fixed": "#dae2fd",
        "on-primary-fixed-variant": "#3f465c",
        "on-tertiary-container": "#009844",
        "tertiary": "#000000",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#131b2e",
        "outline": "#76777d",
        "secondary": "#0051d5",
        "surface-variant": "#e0e3e5",
        "secondary-fixed": "#dbe1ff",
        "on-tertiary-fixed": "#002109",
        "outline-variant": "#c6c6cd",
        "on-error-container": "#93000a",
        "surface-bright": "#f7f9fb",
        "inverse-primary": "#bec6e0",
        "background": "#f7f9fb",
        "secondary-fixed-dim": "#b4c5ff",
        "inverse-on-surface": "#eff1f3",
        "error": "#ba1a1a",
        "on-background": "#191c1e",
        "on-surface": "#191c1e",
        "tertiary-fixed": "#66ff8e",
        "primary-fixed-dim": "#bec6e0",
        "on-secondary-fixed-variant": "#003ea8",
        "surface": "#f7f9fb",
        "on-secondary-container": "#fefcff",
        "surface-tint": "#565e74",
        "on-tertiary-fixed-variant": "#005322",
        "inverse-surface": "#2d3133",
        "on-secondary-fixed": "#00174b",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "surface-dim": "#d8dadc",
        "surface-container-high": "#e6e8ea",
        "on-primary-container": "#7c839b",
        "tertiary-fixed-dim": "#3de273",
        "surface-container-low": "#f2f4f6",
        "on-surface-variant": "#45464d"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-md": "1rem",
        "gutter-desktop": "1.5rem",
        "space-2xl": "3rem",
        "space-2xs": "0.25rem",
        "space-xl": "2rem",
        "gutter-mobile": "1rem",
        "space-4xl": "6rem",
        "space-lg": "1.5rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-3xl": "4.5rem",
        "container-max": "1280px"
      },
      fontFamily: {
        "spec-numeral": ["var(--font-inter)"],
        "label-sm": ["var(--font-inter)"],
        "body-sm": ["var(--font-jakarta)"],
        "headline-lg": ["var(--font-jakarta)"],
        "display-xl-mobile": ["var(--font-jakarta)"],
        "body-md": ["var(--font-jakarta)"],
        "label-md": ["var(--font-inter)"],
        "display-xl": ["var(--font-jakarta)"],
        "headline-lg-mobile": ["var(--font-jakarta)"],
        "headline-md": ["var(--font-jakarta)"],
        "label-lg": ["var(--font-inter)"],
        "body-lg": ["var(--font-jakarta)"],
        "headline-sm": ["var(--font-jakarta)"]
      },
      fontSize: {
        "spec-numeral": ["17px", { "lineHeight": "22px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "label-sm": ["11px", { "lineHeight": "16px", "letterSpacing": "0.04em", "fontWeight": "600" }],
        "body-sm": ["13px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-lg": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "display-xl-mobile": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "body-md": ["15px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-md": ["13px", { "lineHeight": "18px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "display-xl": ["56px", { "lineHeight": "64px", "letterSpacing": "-0.03em", "fontWeight": "800" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.015em", "fontWeight": "700" }],
        "label-lg": ["15px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
};
export default config;
